### ISSUE TITLE
Core dump error

### ISSUE THREAD

**Issue by KramerChristian** [HergenrotherLab/entry-cli#6]
Hi there,

I tried to run your code on a larger dataset of compounds. It seems that at least one of the molecules is not accepted, as I get this error:

[13:44:03] UFFTYPER: Unrecognized atom type: Co5 (43)
Segmentation fault (core dumped)

To figure out which molecule has the problem, I grepped for "Co5" in my file, but there is no hit. The molecule in line 43 also does not have that feature.
From the README, it is not clear to me which types of compounds are accepted and which are not. Could you add some more details to your CLI for this? Also, do the compounds entered have to be neutral or charged, or does this not make a difference?

Thank you,
Christian

**Comment by bdrown** [comment]
The initial guess for molecule geometry uses the Universal force field. UFF doesn't include trigonal bipyramidal cobalt. Are you actually studying cobalt-containing compounds? If not, you may have a typo in one of your SMILES. Either way, this error should be caught instead of seg faulting. I'll work on error handling and some better documentation.

As to your question about charge, things should run fine but this will affect the conformers that are generated. They are generated in gas state, so the conformers for zwitterions can be inaccurate (there's no solvent to screen the charge).
